name: cd

on:
  workflow_call:
    inputs:
      appname:
        required: true
        type: string
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string

env:
  AZURE_WEBAPP_NAME: ${{ inputs.appname }}    # set this to your application's name
  SRCREGISTRY: ghcr.io
  DSTREGISTRY: app1acr.azurecr.io
  IMAGE_NAME: ${{ inputs.image-name }}
  IMAGE_TAG: ${{ inputs.image-tag }}

permissions:
  contents: read

jobs:
  sync-image:
    runs-on: ubuntu-latest
    environment: dev
    env:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.DSTREGISTRY }}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_PASSWORD }}
        
    - uses: bluwy/substitute-string-action@v1
      id: acr_image_name
      with:
        _input-text: ${{ env.IMAGE_NAME }}
        '/': '-'
          
    - run: echo ${{ steps.acr_image_name.outputs.result }}
      
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.SRCREGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        docker pull ${{ env.SRCREGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        docker tag ${{ env.SRCREGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.DSTREGISTRY }}/${{ steps.acr_image_name.outputs.result }}:0.0.1-SNAPSHOT
        docker push ${{ env.DSTREGISTRY }}/${{ steps.acr_image_name.outputs.result }}:0.0.1-SNAPSHOT
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: sync-image
    environment: dev
    env:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    steps:
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ env.DSTREGISTRY }}/${{ steps.acr_image_name.outputs.result }}:0.0.1-SNAPSHOT'
