name: Container Scan

on:
  workflow_call:

env:
  NODE_VERSION: '16.x'                # set this to the node version to use
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
          
      - run: docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      
      - name: Scan image
        uses: Azure/container-scan@v0
        with:
          image-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          severity-threshold: CRITICAL
          run-quality-checks: true      
